import { JSONFile } from "./adapters/JSONFile.js";
import { Low } from "./Low.js";
//import * from "./adapters/JSONFileSync.js";
//import * from "./adapters/LocalStorage.js";
//import * from "./adapters/Memory.js";
//import * from "./adapters/MemorySync.js";
//import * from "./adapters/TextFile.js";
//import * from "./adapters/TextFileSync.js";
//import * from "./LowSync.js";
export default { JSONFile, Low };
